-- +goose Up
ALTER TABLE posts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE posts ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE posts ALTER COLUMN updated_at SET DEFAULT NOW();

-- +goose Down
ALTER TABLE posts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE posts ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE posts ALTER COLUMN updated_at DROP DEFAULT;
